# Generated by Django 4.2.11 on 2024-03-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_departmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(db_index=True, max_length=255, verbose_name='direction_name')),
                ('abbreviation', models.CharField(blank=True, max_length=30, null=True, verbose_name='abbreviation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='main.departmentmodel', verbose_name='department')),
            ],
            options={
                'verbose_name': 'direction',
                'verbose_name_plural': 'directions',
            },
        ),
    ]
