# Generated by Django 4.2.11 on 2024-03-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_directionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=5, verbose_name='number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.directionmodel', verbose_name='direction')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
    ]
