# Generated by Django 4.2.11 on 2024-03-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_groupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePlaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('abbreviation', models.CharField(blank=True, max_length=30, null=True, verbose_name='abbreviation')),
                ('phone_number', models.CharField(max_length=13, verbose_name='phone_number')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('target', models.CharField(max_length=100, verbose_name='target')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_places', to='main.directionmodel', verbose_name='department')),
            ],
            options={
                'verbose_name': 'practice place',
                'verbose_name_plural': 'practice places',
            },
        ),
    ]
