# Generated by Django 4.2.11 on 2024-03-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_groupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePlaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('abbreviation', models.CharField(blank=True, max_length=30, null=True, verbose_name='abbreviation')),
                ('phone_number', models.CharField(max_length=13, verbose_name='phone_number')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('target', models.CharField(max_length=100, verbose_name='target')),
                ('limit', models.PositiveIntegerField(verbose_name='limit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_places', to='main.directionmodel', verbose_name='department')),
            ],
            options={
                'verbose_name': 'practice place',
                'verbose_name_plural': 'practice places',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.departmentmodel', verbose_name='department')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.directionmodel', verbose_name='direction')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.facultymodel', verbose_name='faculty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.groupmodel', verbose_name='group')),
                ('practice_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.practiceplacemodel', verbose_name='practice_place')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
