# Generated by Django 4.2.11 on 2024-03-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_practiceplacemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.groupmodel', verbose_name='group')),
                ('practice_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.practiceplacemodel', verbose_name='practice_place')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
